"""GameForge - Godot 项目生成器

生成完整的 Godot 项目骨架文件：
- project.godot — 项目配置
- default_env.tres — 默认环境
- .godot/ 导入文件
- 场景文件 (.tscn)
"""

import json
import hashlib
from pathlib import Path
from typing import Any, Dict, List, Optional

import structlog

logger = structlog.get_logger()


class GodotProjectGenerator:
    """Godot 项目生成器

    根据 GameDevState 生成完整的 Godot 项目文件。
    """

    def __init__(self):
        pass

    def generate_all(self, state: Dict[str, Any]) -> Dict[str, str]:
        """生成所有项目文件

        Args:
            state: GameDevState 状态字典

        Returns:
            文件字典 {相对路径: 内容}
        """
        files: Dict[str, str] = {}

        project_context = state.get("project_context", {})
        project_name = project_context.get("project_name", "GameForge")
        gdm = state.get("game_design_model", {}) or {}

        # 1. project.godot — 项目配置
        files["project.godot"] = self._generate_project_godot(project_name, gdm)

        # 2. 默认环境
        files["default_env.tres"] = self._generate_default_env()

        # 3. 自动加载脚本（游戏管理器）
        autoloads = self._get_autoloads(state)
        for autoload_name, autoload_path in autoloads.items():
            if autoload_path not in state.get("code_generated", {}):
                files[autoload_path] = self._generate_autoload_script(autoload_name)

        # 4. 输入映射配置
        input_map = gdm.get("input_map", {})
        if input_map:
            files["project.godot"] = self._generate_project_godot(project_name, gdm)

        # 5. 生成 README
        if "README.md" not in state.get("code_generated", {}):
            files["README.md"] = self._generate_readme(project_name, state)

        return files

    def _generate_project_godot(self, project_name: str, gdm: Dict[str, Any]) -> str:
        """生成 project.godot 文件

        Godot 4.x 格式。
        """
        config_version = 5  # Godot 4.x

        # 基础配置
        lines = [
            "; GameForge 生成的 Godot 项目配置",
            "; Generated by GameForge AI Agent",
            "",
            "config_version=5",
            "",
            "[application]",
            "",
            f'config/name="{project_name}"',
            'config/description="由 GameForge AI 自动生成的游戏项目"',
            'config/version="1.0.0"',
            'run/main_scene="res://scenes/main.tscn"',
            'config/features=PackedStringArray("4.2", "GL Compatibility")',
            'config/icon="res://icon.svg"',
            "",
        ]

        # 自动加载
        autoloads = self._get_autoloads_from_gdm(gdm)
        if autoloads:
            lines.append("[autoload]")
            lines.append("")
            for name, path in autoloads.items():
                lines.append(f'{name}="*{path}"')
            lines.append("")

        # 输入映射（兼容 list 与 dict 两种形态）
        raw_input_map = gdm.get("input_map", {}) or {}
        input_map: Dict[str, Any] = {}
        if isinstance(raw_input_map, list):
            for i, item in enumerate(raw_input_map):
                if isinstance(item, dict):
                    name = item.get("name") or f"action_{i}"
                    input_map[name] = item
        elif isinstance(raw_input_map, dict):
            input_map = raw_input_map

        if input_map:
            lines.append("[input]")
            lines.append("")
            for action_name, action_config in input_map.items():
                if not isinstance(action_config, dict):
                    action_config = {}
                deadzone = action_config.get("deadzone", 0.5)
                lines.append(f'{action_name}={{')
                lines.append(f'  "deadzone": {deadzone},')
                lines.append(f'  "events": [')
                events = action_config.get("events", [])
                if isinstance(events, list):
                    for event in events:
                        if isinstance(event, dict) and event.get("key"):
                            key = event.get("key")
                            lines.append(f'    Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":{key},"key_label":0,"unicode":0,"echo":false,"script":null)')
                # 列表形态也可能直接把 key 放在 action 顶层
                elif action_config.get("key"):
                    key = action_config.get("key")
                    lines.append(f'    Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":{key},"key_label":0,"unicode":0,"echo":false,"script":null)')
                lines.append(f'  ]')
                lines.append(f'}}')
            lines.append("")

        # 渲染设置
        lines.extend([
            "[rendering]",
            "",
            'renderer/rendering_method="gl_compatibility"',
            'renderer/rendering_method.mobile="gl_compatibility"',
            "",
        ])

        return "\n".join(lines)

    def _generate_default_env(self) -> str:
        """生成默认环境资源"""
        return '\n'.join([
            '[gd_resource type="Environment" load_steps=2 format=3]',
            "",
            '[sub_resource type="Sky" id="Sky_1"]',
            "",
            '[resource]',
            "background_mode = 2",
            "background_sky = SubResource(\"Sky_1\")",
            "tonemap_mode = 3",
            "ssao_enabled = true",
            "glow_enabled = true",
        ])

    def _get_autoloads(self, state: Dict[str, Any]) -> Dict[str, str]:
        """从状态中获取需要自动加载的脚本"""
        autoloads = {}
        code_generated = state.get("code_generated", {})

        # 检查是否有 GameManager
        for path in code_generated.keys():
            if path.endswith(".gd"):
                filename = Path(path).stem.lower()
                if "gamemanager" in filename or "game_manager" in filename:
                    autoloads["GameManager"] = path
                elif "audiomanager" in filename or "audio_manager" in filename:
                    autoloads["AudioManager"] = path
                elif "scenemanager" in filename or "scene_manager" in filename:
                    autoloads["SceneManager"] = path

        return autoloads

    def _get_autoloads_from_gdm(self, gdm: Dict[str, Any]) -> Dict[str, str]:
        """从 Game Design Model 获取自动加载配置"""
        autoloads = {}
        main_systems = gdm.get("main_systems", [])

        for system in main_systems:
            if isinstance(system, dict):
                name = system.get("name", "")
            elif isinstance(system, str):
                name = system
            else:
                continue

            name_lower = name.lower()
            if "game" in name_lower and "manager" in name_lower:
                autoloads["GameManager"] = "res://scripts/game_manager.gd"
            elif "audio" in name_lower or "sound" in name_lower:
                autoloads["AudioManager"] = "res://scripts/audio_manager.gd"
            elif "scene" in name_lower:
                autoloads["SceneManager"] = "res://scripts/scene_manager.gd"
            elif "input" in name_lower:
                autoloads["InputManager"] = "res://scripts/input_manager.gd"

        # 总是添加 GameManager（如果不存在）
        if "GameManager" not in autoloads:
            autoloads["GameManager"] = "res://scripts/game_manager.gd"

        return autoloads

    def _generate_autoload_script(self, name: str) -> str:
        """生成自动加载脚本"""
        class_name = name.replace(" ", "_")
        return '\n'.join([
            f'## {name} — 由 GameForge 自动生成',
            f'## 自动加载单例，全局可访问',
            f'extends Node',
            f'',
            f'',
            f'func _ready() -> void:',
            f'\tprint("{name} 已初始化")',
            f'',
        ])

    def _generate_readme(self, project_name: str, state: Dict[str, Any]) -> str:
        """生成 README 文件"""
        gdm = state.get("game_design_model", {}) or {}
        task_plan = state.get("task_plan", [])
        code_generated = state.get("code_generated", {})

        genre = gdm.get("genre", "未知")
        description = gdm.get("description", "")

        lines = [
            f"# {project_name}",
            "",
            f"**类型**: {genre}",
            f"**引擎**: Godot 4.x",
            f"**生成文件数**: {len(code_generated)}",
            f"**任务数**: {len(task_plan)}",
            "",
        ]

        if description:
            lines.extend(["## 描述", "", description, ""])

        lines.extend([
            "## 项目结构",
            "",
            "```",
            f"{project_name}/",
            "├── project.godot          # 项目配置",
            "├── scenes/                # 场景文件",
            "├── scripts/               # GDScript 脚本",
            "├── assets/                # 资源文件",
            "└── tests/                 # 测试文件",
            "```",
            "",
            "## 运行方式",
            "",
            "1. 用 Godot 4.x 打开 `project.godot`",
            "2. 按 F5 运行游戏",
            "",
            "---",
            "*由 GameForge AI Agent 自动生成*",
        ])

        return "\n".join(lines)
